### ISSUE TITLE
Gem axes not cutting down full trees

### ISSUE THREAD

**Issue by Elrol** [kreezxil/World-of-Dragons-A-New-Age#10]
I am not fully sure if this is a bug, but vanilla axes cut down the whole tree if you break the bottom block, Silent Gears axes however dont.

**Comment by kreezxil** [comment]
that would indicate for some reason that they might not be based on vanilla
axes. hopefully there's a config for this.

**Comment by kreezxil** [comment]
I'll report this to treechoppin as that is where the compatibility needs to be made

**Comment by kreezxil** [comment]
ok, not treechoppin, as i've already removed that, we're using reap mod. I'll report it there

**Comment by kreezxil** [comment]
reported at https://www.curseforge.com/minecraft/mc-mods/reap-mod/issues/25

it doesn't have a config. I'm going to remove it in favor of 2 mods that should allow the axes to work.
