### ISSUE TITLE
Please disable the mob outline, Very annoying seeing mobs through walls

### ISSUE THREAD

**Issue by Xplodin** [kreezxil/World-of-Dragons-A-New-Age#100]
Since there is no documentation of what mod is causing it i have to open the issue here.

**Comment by kreezxil** [comment]
we know what mod is doing it
the gems mod, however removing it will destroy the world and there are no
configs in the mod to disable the outline

**Comment by kreezxil** [comment]
turns out

it's caused by **The Endergetic Expansion** there is no config to turn it off, if you don't like it remove the mod. I will be removing the mod on the next patch of this pack.

**Comment by kreezxil** [comment]
found it, it's a bug in Forbidden Arcanus. Others have found it too. The Mod author seems unwilling to patch his mod. https://github.com/stal111/Forbidden-Arcanus/issues/48

As of today FA is being removed from the pack.
