### ISSUE TITLE
Simple Storage Network - dupe bug

### ISSUE THREAD

**Issue by Elrol** [kreezxil/World-of-Dragons-A-New-Age#11]
The first was a dupe bug that I had found with Simple Storage Network. I went into detail on the issue and wont do so here. The link to that issue is [here](https://github.com/Lothrazar/Storage-Network/issues/229)

**Comment by kreezxil** [comment]
in the future a brief description, plus the url to the other issue, and one
per issue here. Great job reporting. thanks. the reason for splitting the
issues is that it makes it easier for players and admin to find issues.

**Comment by kreezxil** [comment]
because not everyone knows how to search in the issue tracker search box

**Comment by kreezxil** [comment]
and separate the issues, that's the main thing.

**Comment by kreezxil** [comment]
this mod author has yet to respond.

I cleaned up this overly verbose issue, and separated out the other issue which is fixed.

that's why we have separate issues for each issue else issues stay active when they shouldn't because they were rolled together like a burrito.

Jetpacks issue now at #22

**Comment by kreezxil** [comment]
bug acknowledged, i guess we should be happy that some of them are like Sybok, Spock's half brother from another mother! At least they feel our pain.

![Sybok](https://pbs.twimg.com/media/DANU53SUMAIcdI4.jpg)
