### ISSUE TITLE
Server Not Connecting

### ISSUE THREAD

**Issue by Drapsheik** [kreezxil/World-of-Dragons-A-New-Age#111]
I downloaded Latest Release from Curseforge both for the client and the server.
When running the server it starts properly.
However "unexpected custom data from server" prompts when I try to connect.
Which release is the proper one to connect to the server?

**Comment by kreezxil** [comment]
Did you try to connect to the official public server to verify your test
data? What was the result? The latest release is always the proper release.
Each pack version unless stated otherwise will be accompanied by a
companion server pack.

**Comment by Drapsheik** [comment]
I found the solution. It seems that your latest release has a few differences in config. I managed to make it work by copying the config folder from the server into the latest release. So it would seem that the latest release might not be the proper release unless my download was missing some information or files.

**Comment by kreezxil** [comment]
You do realize that is what you're suppose to do on each update of the pack. It is your responsibility to copy the config folder over no matter what. By holding on to your old configs you are ensuring a nightmare associated with config files that aren't accurate. Config files can change for any number of reasons. 

As of 1.14.4 FORGE itself will reset a config file if it's TOML syntax is wrong. So mod authors are constantly rewriting their mods to not produce bad TOML syntax in the configs. This is just one example and currently the most prevalent reason.

**Comment by Drapsheik** [comment]
No, I didn't realize that. Today was the first time I dealt with 1.15.2 modpacks and the first time I had to copy the config to the latest release and make every person who joined my server copy the config from the server to their respective modpack clients. I apologize for my lack of knowledge, normally when someone downloads a client they are able to join my server right away.
I did not have any previous configurations to the server as I just used the default configurations from the server pack. 

Edit: The first time I dealt with a modpack 1.15.2 which server did not match the config of the latest release. (The first time I dealt with a 1.15.2 modpack server was last night)

Edit 2: I straight up just downloaded the client modpack and the server straight without any changes whatsoever and ran them.

**Comment by kreezxil** [comment]
No, you've taken the concept too far. The server has to have all the updated files from the server pack. The clients automatically have the updated other files. None of the launchers that support auto update ignore the extraneous folders include config/ resources/ etc that we devs include. It was only your server that was missing the correct configs.

**Comment by Drapsheik** [comment]
You say there was an error with my download. Got it, that was the answer I needed. The first answer I got was "get a server online at bisechosting with your code"
Thank you.
Like I said, I am new to this and I had never encountered this error
 That's why I asked and I tried to report something I thought would help. I just downloaded another server from a different modpack, without changes and ran it. Then I connected from the modpack without touching anything else and it worked. I also made my own modpack server to test it out. You are the expert here, not me. That's the reason I asked questions. I want to know for future issues on my side.

**Comment by kreezxil** [comment]
My people will offer a server at bisect hosting because it's an easy way to get you up and running. That said you've clearly learned something.

Based on your experience, and this is the case each time someone reports and issue like yours. This is what I do.

1. remove my own development server that the pack is built on.
1. remove my own development client that the pack is built on.
1. download the server the ticket is having the issue with
1. install that pack fresh in the launcher

yes I have backups.

In this particular instance, there were no issues connecting the client to the server. I felt no need to explain it further based on our ticket conversation, but now I have.
