### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#13]
Not sure what exactly caused this. Sleeping, woke up to zombies, started casting my magic at them, after 4-5 casts game crashed. Here is the attached report.
[crash-2019-10-30_11.35.31-client.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3789841/crash-2019-10-30_11.35.31-client.txt)

**Comment by kreezxil** [comment]
learn to use https://paste.ubuntu.com, then i won't have to download your file each time.

**Comment by kreezxil** [comment]
if you read the crash report you can see that it's complaining about minecolonies and permission event.

**Comment by kreezxil** [comment]
Minecolonies dev team this is the result of a corrupted jar, ie, the pack corrupted you will have to delete the pack and reinstall the pack.
