### ISSUE TITLE
New mod suggestion by Azureprincess

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#14]
Dungeon Crawl
because who doesnt like a good dungeon crawl lol
https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl

**Comment by kreezxil** [comment]
really? these dungeons are going to hurt

**Comment by kreezxil** [comment]
added, if it doesn't crash, you'll see it in the update.
