### ISSUE TITLE
[mod suggestion] A bunch of mods

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/World-of-Dragons-A-New-Age#15]
[Extra golems for a little magic construct spice.](https://www.curseforge.com/minecraft/mc-mods/extra-golems)

[Mystical Wildlife because the mountains are devoid of life and could use a few furry lizards.](https://www.curseforge.com/minecraft/mc-mods/mystical-wildlife)

[Doggy talents to live the WoW hunter fantasy.](https://www.curseforge.com/minecraft/mc-mods/doggy-talents)

Of course, test and check if they work with all the other mods (I think they should with what we have but I haven't looked very thoroughly deep into them).

**Comment by kreezxil** [comment]
we'll test and check them live, i'm only going to see if they crash a server or client on startup.
