### ISSUE TITLE
Mod Suggestions Azureprincess

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#17]
https://www.curseforge.com/minecraft/mc-mods/inventory-sorter
Sorting inventory is heaven on minecraft.
https://www.curseforge.com/minecraft/mc-mods/move-plus
it looked interesting so i thought maybe you might like to add this.
https://www.curseforge.com/minecraft/mc-mods/deathquotes-death-quotes
Because we need better some funny quotes to go with our swimming in lava.
https://www.curseforge.com/minecraft/mc-mods/config-checker
I wasnt sure about this but I figured if it could help out to make your job easier than i would suggest it.

**Comment by kreezxil** [comment]
inventory sorter is already in the pack, not sure how you missed that

config-checker is for making sure that players don't tamper with my packs.
but why bother. if you're playing single player tweak the config, or your
own private server, again go tweak the config.

I'll look at the other two later.

**Comment by Azuraprincess** [comment]
Oh I didnt notice because when I tried to sort inventory it wasnt working maybe it's just not set as a key bind. As for the config ya I didnt understand it, it looked like someone to help you which is why I suggested it.

**Comment by kreezxil** [comment]
also in the future make one mod request per issue. it's just easier that way, especially in the event that someone decided to start conversations on about them.

Where possible, mods have been added, wait for the changelog for actual evidence.
