### ISSUE TITLE
mod suggestions

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/World-of-Dragons-A-New-Age#18]
Refined Storage
  we always need more kinds of storage systems
https://www.curseforge.com/minecraft/mc-mods/refined-storage

**Comment by kreezxil** [comment]
please search before you recommend. make sure it is available for the mc
version we are on and the type of mod loader. Currently Refined Storage is
not available for 1.14.4 Forge.

**Comment by xxkainexx** [comment]
hmmm well on the files the latest one is for minecraft 1.14 (refined storage 1.7)

**Comment by WolfBV** [comment]
https://www.curseforge.com/minecraft/mc-mods/refined-storage/files/2820669

**Comment by Elrol** [comment]
I would LOVE this in the pack, my only worry is that it is alpha so who knows what could break. 
I was about to start setting up 'autocrafting' by having some crafters piped full of stuff and just have them on hand (stuff for minecolonies mainly) this would be amazing if we can

**Comment by kreezxil** [comment]
last week it wasn't ported. and yes in the future always give the links,
don't expect me to have the time to do it.

i'll get that added to a patch later today.

thank you for your time

**Comment by kreezxil** [comment]
yeah this was ported 2 days ago, he's disabled quite a bit of stuff. it'll be interesting to see if it causes server lag.

added!
