### ISSUE TITLE
Crash report for a crash that happens when trying to get onto server

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#20]
[crash-2019-11-04_14.56.41-client.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3805826/crash-2019-11-04_14.56.41-client.txt)

**Comment by Azuraprincess** [comment]
solved

**Comment by kreezxil** [comment]
how was it solved?
