### ISSUE TITLE
Cant create a colony

### ISSUE THREAD

**Issue by Martinose1** [kreezxil/World-of-Dragons-A-New-Age#23]
On the official sever. Cant access the townhall gui after placing it. Colonists don't spawn and the colony border is non-existent. It's been like that since the wipe.

**Comment by kreezxil** [comment]
we're using dynamic colony borders now.

**Comment by CriswellCodes** [comment]
This issue has been resolved using operator powers. Report has been made to Minecolonies development team. The interaction and inability to create a new townhall while being an "Offiicer" in another colony appears to be the issue. Martinose1 now has his colony established.

**Comment by kreezxil** [comment]
I need the minecolonies issue link pasted into this thread. @Tarlin83

**Comment by CriswellCodes** [comment]
https://github.com/ldtteam/minecolonies/issues/3885

Issue link for the latest.

**Comment by CriswellCodes** [comment]
Seems that the run on issue is that something is causing a "building tool: null!" interaction

**Comment by CriswellCodes** [comment]
https://paste.ubuntu.com/p/Z9pXtcYpw2/
Line 413 of the server log represents the error

https://paste.ubuntu.com/p/Vfz9Ng8Y7Z/
Line 227 of the player log also represents the error

**Comment by kreezxil** [comment]
@Tarlin83 are these lines your noting, are they noted at https://github.com/ldtteam/minecolonies?

**Comment by CriswellCodes** [comment]
Yes and no. The issue is noted and the lines were specified but because it is unreproducible I was told not to add it to the gist. They were already tracking the issue.

**Comment by CriswellCodes** [comment]
Discussion was had in the minecolonies discord directly prior to doing anything on the github. They linked me the current tracker from their GitHub that I posted above.

**Comment by kreezxil** [comment]
bug has been acknowledged but not fixed ... hmm
