### ISSUE TITLE
Shape Card doesn´t work on the Server

### ISSUE THREAD

**Issue by LordJustin53** [kreezxil/World-of-Dragons-A-New-Age#24]
I wanted to use the builder from RF Tools on the WODNA Server.  Then i crafted a Shape card (Quarry clearing). The i clicked on the builder with the shape card, set the first and second corner. Then i looked in the shape card with right click. There was all correct configurated, but it set #Blocks 0. I did see the Area i selected, but like i sad, 0 Blocks. Then i´ve put the card in the builder an like I expected it doesn´t work.

I tried in Single Player and it worked there.

**Comment by kreezxil** [comment]
now post on the rftools mod that has the builder, and give them all the
information they require to fix the bug. then after you submit it, copy the
link for the issue and paste that issue here. that will complete your issue
submission.

again thanks for your report.

**Comment by kreezxil** [comment]
@LordJustin53 please goto https://github.com/McJtyMods/RFToolsBuilder/issues and create an issue there, be as specific as possible. I have no idea why McJty is hiding his issue tracker.

**Comment by kreezxil** [comment]
can't follow instructions, closing this. we can't get fixed wont you help us to generate data for @LordJustin53
