### ISSUE TITLE
[please add] GamemodeOverhaul

### ISSUE THREAD

**Issue by WolfBV** [kreezxil/World-of-Dragons-A-New-Age#28]
Mod Name: GamemodeOverhaul
Mod Link: https://www.curseforge.com/minecraft/mc-mods/gamemodeoverhaul/files/2800169 

Reason: Adds in a command to set the default gamemode for worlds, can be used to set the default gamemode of the world to survival.

**Comment by AzureDoom** [comment]
The game mode is currently set to adventure due to moving the player data over when the world was reset to fix the biomes. I'm sure Kreezxil will set it back to survival here soon since I believe everyone has logged in that would need it.

**Comment by kreezxil** [comment]
this is pointless because server.properties can be used for that. Also I put everyone in adventure mode when we did the wipe last to prevent them from spawning in mountains or trees and a die-ing.

**Comment by kreezxil** [comment]
oh and if an op in creative logs out as creative, they should log back as op in creative, else it will feel broken.
