### ISSUE TITLE
Minecolonies CitizenData.View in 0.10.518 index out of bounds client crash

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons-A-New-Age#34]
https://github.com/ldtteam/minecolonies/issues/4050

**Comment by CriswellCodes** [comment]
Appears that this is nearing a resolution....
https://github.com/ldtteam/minecolonies/pull/4061

**Comment by kreezxil** [comment]
the linked reports say the fix has been applied. therefore today's update has the fix too.
