### ISSUE TITLE
Badwithernocookies client side error report - crash

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#35]
GrveCrvr spawned 2 withers, after spawning the second with it threw all sorts of exceptions and crashed both of our games as we were loaded into the same chunk. No other players online were affected. Issue did not occur until 2 withers were spawned at same time in same chunk.

https://paste.ubuntu.com/p/RBTp2KtnnQ/

**Comment by kreezxil** [comment]
my own mod, but i have a programmer that is responsible for the 1.14.4 branch.

**Comment by kreezxil** [comment]
I fixed this myself considering that my programmer has gone awol. In the next update this will no longer be an issue.
