### ISSUE TITLE
[Bug] Token Enchanting Spikes Dupe

### ISSUE THREAD

**Issue by Elrol** [kreezxil/World-of-Dragons-A-New-Age#37]
Basically using a token to enchant any number of spikes greater then 1 (2-64) will output that same amount, with the enchant, but  only decrease the stack inputed by 1, This should be a simple fix by checking the stack size of the item and only outputing a single one, not a full copy of the stack with the enchant.

**Comment by CriswellCodes** [comment]
Made report to silent mods creator, cross linked here.

https://github.com/SilentChaos512/Silent-Gear/issues/76

**Comment by kreezxil** [comment]
bug has been acknowledged. but not yet fixed.

**Comment by Elrol** [comment]
Good to know.
