### ISSUE TITLE
Crash Report using Refined Storage after awhile

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#38]
[crash-2019-11-08_00.26.17-client.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3823098/crash-2019-11-08_00.26.17-client.txt)

**Comment by kreezxil** [comment]
this would've fitted on pastebin, :(

**Comment by kreezxil** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/2345

**Comment by kreezxil** [comment]
acknowledged, might or might not be fixed this update
