### ISSUE TITLE
Player log for examination

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#4]
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3775225/latest.log)

**Comment by Azuraprincess** [comment]
[2019-10-25-5.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3775232/2019-10-25-5.log)

**Comment by kreezxil** [comment]
i can't find anything useful in there. Try placing some other type of structure besides acacia, or try placing the townhall block and then selecting the type from the build options.
