### ISSUE TITLE
[Suggestion] Incease the enchanting limit with apotheosis.

### ISSUE THREAD

**Issue by Elrol** [kreezxil/World-of-Dragons-A-New-Age#45]
The only reason that I am suggesting it, is because the current max enchanting level, is not high enough to get all of the enchants, like life mending (not really that good since it takes hp to repair, but its an example) 

The information on each enchant (with a few exceptions) can be found [here](https://gist.github.com/Shadows-of-Fire/adab31e668b4fe71578bae2d5f87ee2b)

(ep is enchanting power, currently capped at 20 vanilla and 50 hellshelf)

- Berserker's Fury 4 : 120 ep *
- Miner's Fervor 7 : 79 ep
- Hell Infusion 10 :  120 ep *
- Icy Throns 3 : 85 ep *
- Life-Mending 3 : 125 ep *
- Mounted Strike 7 : 57 ep 
- Reflective Defenses 5 : 76 ep
- Scavenger 3 : 153 ep *
- Shield Bash 5 : 45 ep
- Stable Footing 1 : 40
- Tempting 1 : 0 ep
- Knowledge of the Ages 3 : 74 ep
- Splitting 5 : 60 ep
- Rebounding 3 : 51 ep
- Occult Aversion 4 : 115 ep

Those are the minimum enchanting levels to get the maximum level of each enchant. The ones marked with the * are currently unable to be gotten.

I would suggest maybe bumping the enchanting to 30 vanilla, and 100 hellshelf, or 50 vanilla and 120 hellshelf, or somewhere in there. But it is just a suggestion.

**Comment by kreezxil** [comment]
thanks for providing configs!!!

**Comment by kreezxil** [comment]
The config file apotheosis/enchantments.cfg is not as straightforward as your own words. I don't feel like digging thru their documentation. 

What I'm going to do is wait for you edit the file on your end and then submit it to this tracker. Once received it will go in either todays update or the whenever update.

**Comment by Elrol** [comment]
Sounds like a plan. When I get up I will tweak the file and upload it straight away.

**Comment by CriswellCodes** [comment]
Tried looking into this myself and see the confusion the Kreezxil experienced.
This is the information provided by you @Elrol in the link above for Berserkers Fury:

Berserker's Fury
Equipment Slots: Chest, Legs
Minimum Enchantment Power: 60 + level * 15
Maxiumum Enchantment Power: 100 + level * 15
Maxiumum Level: 4
Enchantment Types: Corrupted
Effect: When damaged, the player will take an additional level * level corrupted damage and gain 200 * level ticks of Resistance, Strength, and Speed. Potion levels are equivalent to enchantment level. Multiple enchantments can stack, the sum of all levels will be treated as the level. The effect will not trigger if the user has resistance active.

This is the translation in the enchantments.cfg file:
"apotheosis:berserk" {
    # The max level of this enchantment. [range: 1 ~ 127, default: 4]
    I:"Max Level"=3

    # A function to determine the max enchanting power.  The variable "x" is level.  See: https://github.com/uklimaschewski/EvalEx#usage-examples [default: ]
    S:"Max Power Function"=

    # The min level of this enchantment. [range: 1 ~ 127, default: 1]
    I:"Min Level"=1

    # A function to determine the min enchanting power. [default: ]
    S:"Min Power Function"=
}

Do I just need to plug in the Min and Max enchantment power after:   # A function to determine the min enchanting power. [default: ]
    S:"Min Power Function"= 60
As an example.?

Curious as to how this one works seems super simplistic but very confusing based of the wording. I would assume that there needs to be an algorithm to establish the "Minimum Enchantment Power: 60 + level * 15" that is represented by the authors in your linked git post.

**Comment by Elrol** [comment]
Um. well what I was thinking was just to change the other file instead of redoing all of the enchants like that we could just change the "enchantment_module.cfg" from this:
`general {
    # If cobwebs can be used in anvils to remove enchantments. [default: true]
    B:"Enable Cobwebs"=true

    # If any two enchanted items can be combined in an Anvil. [default: false]
    B:"Item Merging"=true

    # The maximum enchantment power a table can receive from normal sources. [range: 0.0 ~ 3.4028235E38, default: 20.0]
    S:"Max Normal Power"=20.0

    # The maximum enchantment power a table can receive. [range: 0.0 ~ 3.4028235E38, default: 75.0]
    S:"Max Power"=50.0
}`

To this:

`general {
    # If cobwebs can be used in anvils to remove enchantments. [default: true]
    B:"Enable Cobwebs"=true

    # If any two enchanted items can be combined in an Anvil. [default: false]
    B:"Item Merging"=true

    # The maximum enchantment power a table can receive from normal sources. [range: 0.0 ~ 3.4028235E38, default: 20.0]
    S:"Max Normal Power"=20.0

    # The maximum enchantment power a table can receive. [range: 0.0 ~ 3.4028235E38, default: 75.0]
    S:"Max Power"=120.0
}
`

or something like that. It would do basically the same thing and allow all the enchants to be gotten, but thats up to you which you would like to be changed

**Comment by CriswellCodes** [comment]
Changed Enchantment_module.cfg to reflect the base default configs as represented in the .cfg

~~~
general {
    # If cobwebs can be used in anvils to remove enchantments. [default: true]
    B:"Enable Cobwebs"=true

    # If any two enchanted items can be combined in an Anvil. [default: false]
    B:"Item Merging"=true

    # The maximum enchantment power a table can receive from normal sources. [range: 0.0 ~ 3.4028235E38, default: 20.0]
    S:"Max Normal Power"=20.0

    # The maximum enchantment power a table can receive. [range: 0.0 ~ 3.4028235E38, default: 75.0]
    S:"Max Power"=75.0
}

~~~

This incorporated smoothly, no bugs on testing.

@kreezxil

**Comment by kreezxil** [comment]
added to the production server and the next modpack release (which won't happen today)
