### ISSUE TITLE
[please fix] Ethane and Polyethylene bug/glitch/lack of feature

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/World-of-Dragons-A-New-Age#48]
These fluids from Silent's Mechanisms do not have a bucket equivalent (ie, for diesel there's diesel as the standalone fluid but there's also diesel bucket) which means lost buckets if you try to interact with them with a fluid grid (canisters do NOT work) and you can't make fluid filters for refined storage with these two.

**Comment by kreezxil** [comment]
This is a silent's mechanism issue. We need this reported on Silent's
Mechanism and then crosslink pasted here.

**Comment by CriswellCodes** [comment]
https://github.com/SilentChaos512/Silents-Mechanisms/issues/49

Crosslink provided. @T0uchMeSenpai please check the above link for accuracy.
