### ISSUE TITLE
Minecolonies bug 

### ISSUE THREAD

**Issue by Newt121** [kreezxil/World-of-Dragons-A-New-Age#49]
I got only 2 chunks in my colony claimed and when i upgrade buildings nothing happends still just 2 chunks 
![2019-11-13_01 51 58](https://user-images.githubusercontent.com/57691826/68723225-46e8ba80-05b8-11ea-87b3-d37a2a42d63c.png)

**Comment by CriswellCodes** [comment]
The server is using Dynamic borders, as you level up your building it will expand your borders. Placing a guard tower or other buildings will also expand your borders. Using Dynamic border settings if you space out too much it may leave chunks unclaimed in your village.

If this has not resolved your issue please update the post with more detail so it can be reproduced and reported. I do think this is just Dynamic borders.

**Comment by CriswellCodes** [comment]
@Newt121

**Comment by kreezxil** [comment]
don't look at your border and say to yourself, oh shiznat this is broken!
just place the new building.

**Comment by kreezxil** [comment]
the building will have to be placed somewhere on the existing border is the
only requirement.
