### ISSUE TITLE
Player log for review

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#5]
[2019-10-26-4.log.gz](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3775972/2019-10-26-4.log.gz)
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3775973/latest.log)

Attached the log.gz and the text log of the latest instances of the game. Game crash but no actual crash report created or reason given in the launcher. Might have been client side.

**Comment by kreezxil** [comment]
what I really need is the crash report, found in the crash-reports/ folder.

**Comment by GraveCarver** [comment]
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3776020/latest.log)
[2019-10-26-7.log.gz](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3776021/2019-10-26-7.log.gz)

there are no crash report logs for any of this, seems to be the said memory leak issue.

**Comment by kreezxil** [comment]
totally not a memory leak, but a curio issue, which one tho.

[22:31:35] [Client thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
at
top.theillusivec4.curios.common.capability.CapCurioInventory$CurioInventoryWrapper.setStackInSlot(CapCurioInventory.java:178)
~[?:FORGE-1.14.4-1.0.5]
at
top.theillusivec4.curios.common.network.server.sync.SPacketSyncContents.lambda$null$0(SPacketSyncContents.java:67)
~[?:FORGE-1.14.4-1.0.5]
at
top.theillusivec4.curios.common.network.server.sync.SPacketSyncContents$$Lambda$7265/1873813813.accept(Unknown
Source) ~[?:?]
at
net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
~[?:?]
at
top.theillusivec4.curios.common.network.server.sync.SPacketSyncContents.lambda$handle$1(SPacketSyncContents.java:67)
~[?:FORGE-1.14.4-1.0.5]
at
top.theillusivec4.curios.common.network.server.sync.SPacketSyncContents$$Lambda$7264/803901773.

**Comment by kreezxil** [comment]
same crash in tarlin's log

**Comment by GraveCarver** [comment]
Would that be a cause if one of the curio rings we have? Only one in our inv is the magnetic one. Also i seemed to have allot of open Gl errors, which maybe reverting my java update back may fix that.

**Comment by kreezxil** [comment]
the opengl errors are nothing, Open GL means Open Graphics Library. It's
what the 1.14.4 FORGE is using to render graphics. Just ignore it because
1.14.4 FORGE is BETA. it's not an issue unless you see artefacts on your
screen.

**Comment by GraveCarver** [comment]
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3786308/latest.log)
 no log.gz files or crash reports
