### ISSUE TITLE
Mod Request: Mine and Slash Auto Compatibility

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#50]
AzureDoomC has worked to create a compatibility mod that will make Mine and Slash applicable to all CURRENT gear and weapons in the WoD-NA modpack. Would like to have it added please.

https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-auto-compatibility

**Comment by kreezxil** [comment]
added
