### ISSUE TITLE
Mod Request: random things

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/World-of-Dragons-A-New-Age#51]
Random Things
https://www.curseforge.com/minecraft/mc-mods/random-things/files/all?filter-game-version=1738749986%3a64806

It's fun to just have a handful of random things to play with.

**Comment by kreezxil** [comment]
he's got some stuff in it that I don't want in the pack. I used to install
that mod religiously.

**Comment by xxkainexx** [comment]
couldn't you disable the ones you don't want in there?

**Comment by kreezxil** [comment]
that's not that easy, never has been, when crafttweaker was a thing, I
could knock out recipes. i'll be experimenting today with knocking out
recipes in Blue Power if not the block itself.

**Comment by kreezxil** [comment]
I don't have a way to knock out recipes yet and i'm not skilled enough in datapacks to knock them out.

I need to be able to remove "time in a bottle" i know that's the only reason you requested this mod, you want to bring my server to crawl just so you can process faster. shame on you.

and the easy end portal needs to be removed.
