### ISSUE TITLE
Crash: Blue electric Alloy Furnace

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#52]
Game is being forced to close and crash on the server side due to the Alloy Furnace by Blue Electric causing a tick delay that is substantial. It is triggering a watchdog alert due to the ticking time increasing rapidly on the server.

Crash Log:

https://paste.ubuntu.com/p/jZ59srgQSD/

Mod: Blue Electric
Version: bluepower-1.14.4-0.3.147-alpha

Crosslink:
https://github.com/Qmunity/BluePower/issues/512

**Comment by CriswellCodes** [comment]
Full crash log for tracking needs
https://paste.ubuntu.com/p/csRZ9kXGK9/

**Comment by kreezxil** [comment]
mod author has acknowledged the bug

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.151-alpha and have uploaded to curse.
