### ISSUE TITLE
Remove Mod Item: Blue Electrics Alloy Furnace

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#53]
So it appears that the issue of the Alloy furnace attached to hoppers causing the extreme tick and server crash. A lot of players have built up using Blue Electric mod, so removing it would cause a big issue. Is it possible to just disable or remove Alloy Furnaces from the mod and game for the time being until they fix the issue?

**Comment by kreezxil** [comment]
please also report th is on the blue power mods tracker.

**Comment by CriswellCodes** [comment]
Was trying to just remove from our server so that Newt121 can play. Currently his base is the only one setup in a way that it is causing the whole server to crash.
