### ISSUE TITLE
Shield not gaining Mine and Slash stats.

### ISSUE THREAD

**Issue by AzureDoom** [kreezxil/World-of-Dragons-A-New-Age#55]
Was informed that shields aren't getting Mine and Slash stats. Opening a ticket here so you know about it.

**Comment by AzureDoom** [comment]
https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-auto-compatibility/files/2827789 fixed in the new update.

**Comment by kreezxil** [comment]
updated
