### ISSUE TITLE
Mod Suggestion: Pick Up Notifier

### ISSUE THREAD

**Issue by AzureDoom** [kreezxil/World-of-Dragons-A-New-Age#56]
Link to mod: https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier

Reasoning: As the mod is centered around picking up loot, this simple GUI mod can keep track of the gear we get without having to always stop and look at our inventories.

**Comment by kreezxil** [comment]
so it picks stuff up?
it notifies you when it picks stuff up?
it notifies you when stuff you picked up is better than the stuff in your
hot bar and your armor slots?

**Comment by CriswellCodes** [comment]
So after downloading and toying with this on single player, it appears that the only thing it does is give a display on the right side that lists the name of the item that you picked up and the quantity. This might help some players that are out mining or using something to bulk break blocks like a drill or a pick that does 3x3x1 breaking like the etherium pickaxe to see exactly what was collected. It is mostly a QOL mod so you don't have to open your inventory to see how much of an item you picked up. After a certain amount of time the display on the lower right hand side will fade away and not be visible if you have not picked up an item of that sort for a period of time.

It will not tell you if the gear is better than what you have currently equipped, although that would be cool. It does not pick up stuff for you either, not like the magnetic ring. It will only tell you when you have a new item or new quantity of items in your inventory.

This might also be helpful when a player dies to ensure that they collected everything that was dropped without having to open their inventory while in a hostile environment.

**Comment by kreezxil** [comment]
added
