### ISSUE TITLE
Mod Suggestion: Crafttweaker

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/World-of-Dragons-A-New-Age#57]
Craft tweaker
https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/2827217
Because you wanted to be able to remove recipes so this will work.

**Comment by kreezxil** [comment]
this will not work. just because it's released for 1.14.4 it's not ready
for 1.14.4. I'm way ahead of you on this.

**Comment by xxkainexx** [comment]
Ah well i tried.

**Comment by kreezxil** [comment]
added on the off-chance it actually begins to work
