### ISSUE TITLE
Crash: Refined Storage Portable Crafting Grid

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#58]
When looking inside of the portable crafting grid provided by refined storage, and another player breaks the grid to pick it up, forces the player looking in the inventory to crash.

Crash report:
https://paste.ubuntu.com/p/DsvssvGz67/

Mod: Refined Storage	
Dev: raoulvdberge	
Version: refinedstorage-1.7.jar
Forge 28.1.87
Minecraft: 1.14.4

Crosslink will be provided when issue posted to mod momentarily

**Comment by CriswellCodes** [comment]
yay, it crosslinked! 
But just because I can
https://github.com/raoulvdberge/refinedstorage/issues/2353

**Comment by CriswellCodes** [comment]
Dev has acknowledged this as a bug.

**Comment by kreezxil** [comment]
the dev needs to get around to fixing the bugs. but what we can do, we can't just rip it out, too many people have made drives. I should've disabled the drives. stupid me.

**Comment by CriswellCodes** [comment]
The Dev is a bit of an asshole, but this is fixed.

**Comment by kreezxil** [comment]
fixed and updated

**Comment by kreezxil** [comment]
Reopening because it appears to still be a problem.

**Comment by raoulvdberge** [comment]
This has been fixed and is no longer a problem. The author of #74 said that he couldn't replicate it no longer after the update.

**Comment by kreezxil** [comment]
thank you
