### ISSUE TITLE
Mod Suggestion Aquaculture 2

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#59]
https://www.curseforge.com/minecraft/mc-mods/aquaculture
Add more fishes to the roster of fish to fish, as well as some interesting new crafts from the said fishing.

**Comment by CriswellCodes** [comment]
Seems pretty cool, actually would add a lot of reason to fish in order to obtain the Neptunian armor.

**Comment by kreezxil** [comment]
added

## At some point we're going to have to stop adding mods
as we're becoming All The Mods 5 easily.
