### ISSUE TITLE
New mod Suggestions

### ISSUE THREAD

**Issue by GraveCarver** [kreezxil/World-of-Dragons-A-New-Age#6]
-Lycanites mobs
          because we all wanted a more difficult world to live in. since we no longer have all the mobs from Ice and Fire, i think this would be a good mod to add in.

https://www.curseforge.com/minecraft/mc-mods/lycanites-mobs

-Draylars Battle Towers
           adds some structures that give a challange to players. if it doesnt break the game, would be interesting to add

https://www.curseforge.com/minecraft/mc-mods/draylars-battle-towers

I do not know if these will cause any major issues with any mods installed as one adds a world generation structure, while the other one adds mobs. only mine and slash would affect them the most as far as i know, i have not tested it yet.

**Comment by WolfBV** [comment]
Draylar’s Battle Towers might break the game with its Fabric only-ness ;p

**Comment by T0uchMeSenpai** [comment]
I like the mount/pet system in lycanites, and the equipment system buuuuut... the equipment will likely not scale with MS stats. Granted, the added random mobs could be fun in a scaling world (but then again, I also encountered a skeleton horde early in).

**Comment by kreezxil** [comment]
fabric and rift mods do not run in forge packs.

the pack is hard enough, i can change the diff to 3, it's on easy now,
which I'm finding to be a bit hard. Also you guys only think it's easy
because you are sleeping the mobs away with morpheus. meaning that not only
will i have to remove morpheus, but I will have to add a mod that prevents
regular bed sleeping from advancing the night.

also no to lycanites, lycanites with what we got will be unbearable.

**Comment by GraveCarver** [comment]
Well i mean, i didnt find it easy, since the only reason we was forced to sleep was because of the retarded phantoms that never end if you dont sleep. And where we built our colony mobs seem to never end spawning on our large flat area during the night making it impossible to do much else but slaughter our way out of hell and run.  The amount of times i watched tarlin get steam rolled by a horde of zombies or slimes has had me laughing more then i should

**Comment by kreezxil** [comment]
Good news my good buddy Raycoms aka h3lay of Minecolonies fame has coded a
mod that eliminates the phantoms. I'll add it next patch.

**Comment by kreezxil** [comment]
yeah, i'm closing this, lycanites is too much and we already established the fabricness of the other.
