### ISSUE TITLE
Mod Suggestion Koratio Dimension mod

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#61]
https://www.curseforge.com/minecraft/mc-mods/koratio
So I figured a new dimension would be nice and it wouldnt tamper with the overworld dimension so we dont have to worry about biome problems.

**Comment by CriswellCodes** [comment]
As cool as this actually appears to be, there might be a conflict. With the most updated changelog that the dev put out, it has this line:
Changes:
- Updated to 28.1.40 Forge

We are running forge 28.1.87
Not sure if this would cause conflict.

**Comment by Azuraprincess** [comment]
Oh just noticed the but i guess testing it on the dev server would show whether their would be any problems right?

**Comment by kreezxil** [comment]
You guys don't understand forge versioning very well. If the pack was
running on a forge version less than the one compiled for the mod then
there would be a problem. All we have to do is meet or exceed the forge
version.

**Comment by CriswellCodes** [comment]
In fairness that is why I posed the question. Thank you for the explanation 🥇

**Comment by kreezxil** [comment]
added
