### ISSUE TITLE
Minecolony Crash.

### ISSUE THREAD

**Issue by GraveCarver** [kreezxil/World-of-Dragons-A-New-Age#65]
Minecolony Crash report
https://pastebin.com/Aai8u77w

Latest log file showing error report
https://pastebin.com/ffcVWS8w

**Comment by CriswellCodes** [comment]
Can you give a description of how this occurred....

**Comment by kreezxil** [comment]
this may or may not be fixed in todays update. we'll soon see.

**Comment by kreezxil** [comment]
make sure this is cross posted to minecolonies team, it's an issue with
client rendering as indicated by the top of the stack trace.

**Comment by kreezxil** [comment]
3 days old, no cross link, i'm going to close it.
