### ISSUE TITLE
[Mod Needs Updated] Aquaculture and Good Night Sleep not Mine and Slash compatible. 

### ISSUE THREAD

**Issue by AzureDoom** [kreezxil/World-of-Dragons-A-New-Age#66]
Just posting this here as a reminder. I have updated M&S AC to support those two mods, among a ton of others that aren't in the pack but if added in the future will link right into the Mine and Slash system.

**Comment by kreezxil** [comment]
your title is so confusing and foreboding

**Comment by AzureDoom** [comment]
As it should be. It's foreboding of the complaints that those mods don't gain stats :P

**Comment by kreezxil** [comment]
updated
