### ISSUE TITLE
Mod Removal Request: Koratio

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#68]
Mod is causing significant hangtime errors when encountering objects from the mod. 

Crash report:
https://paste.ubuntu.com/p/pYH7Cs794q/

Players are crashing both client and server but only when interacting with this mod. Please remove.

Mod: Koratio	SetrionGaming	koratio-1.14.4-0.0.8-beta.jar

**Comment by kreezxil** [comment]
has it been reported on the authors tracker?

**Comment by kreezxil** [comment]
https://www.curseforge.com/minecraft/mc-mods/koratio/issues/14

and he does check this tracker at all. so, yeah removed.

**Comment by kreezxil** [comment]
The mod author denies fault. please go there and tell him your experience.
