### ISSUE TITLE
Doing /sethome <alreadycreatedhome> does not update that home to new location

### ISSUE THREAD

**Issue by AzureDoom** [kreezxil/World-of-Dragons-A-New-Age#69]
When a player first sets a home using /sethome, it creates a default home. When a player moves and tries to do /sethome home, it's not updating the default home location, instead teleporting to the new updated home location.

1. Create a home using /sethome
2. Move to another location and do /sethome home
3. Do /home home 
4. You are moved to the old location instead of the new location.

**Expected behavior**
What is expected is that using the /sethome <alreadycreatedhome> command updates the home location to the new one. 

**Versions**
- **Ma Essentials**: 1.2.4
- **Forge**: 1.14.4

This is just a cross link for your records of Maciej916/Ma-Essentials#20

**Comment by Elrol** [comment]
you could swap to a better mod like server utils :3

**Comment by derGrinch69** [comment]
workaround: first /delhome home and then /sethome home  - worked for me

**Comment by kreezxil** [comment]
we're going to switch to a better mod now.

**Comment by AzureDoom** [comment]
Just putting this here for future use if this mod is added back. This was fixed in the 1.2.5 release.
