### ISSUE TITLE
TheRCMod causing a crash when launching

### ISSUE THREAD

**Issue by WolfBV** [kreezxil/World-of-Dragons-A-New-Age#7]
**Describe the bug**
Using the vanilla minecraft launcher with forge, attempting to launch the forge instance with TheRCMod as the only mod in the mods folder, Minecraft closes itself while loading mods and a "Java has quit unexpectedly" error window pops up

**To Reproduce**
1. Install Forge for 1.14.4 version 28.1.70
2. Install the client version to create a forge minecraft instance
3. Add TheRCMod to your mods folder
4. Launch the forge instance using the vanilla minecraft launcher

**Screenshots**
![Screen Shot 2019-10-27 at 9 19 53 PM](https://user-images.githubusercontent.com/47493126/67651857-b21b6700-f8ff-11e9-8208-ad83ccb3b8de.png)
![Screen Shot 2019-10-27 at 9 20 25 PM](https://user-images.githubusercontent.com/47493126/67651860-b21b6700-f8ff-11e9-9fbd-170f937319a6.png)
![Screen Shot 2019-10-27 at 9 20 36 PM](https://user-images.githubusercontent.com/47493126/67651862-b21b6700-f8ff-11e9-98bc-aa7edd2c1799.png)

**Versions:**

 - Minecraft: 1.14.4
 - Forge: 28.1.70
 - Mod Pack : World of Dragons - A New Age-1.2.3
 - Mod Name: TheRCMod
 - Mod Version: v.4.0.0.0

**Logs**

Crash Report: 
[crash-2019-10-27_16.07.12-client.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3777123/crash-2019-10-27_16.07.12-client.txt)

Debug Log: 
[debug.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3777107/debug.log)

Latest Log:
[latest.log](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3777109/latest.log)

**Additional context**
Java quit unexpectedly log: https://pastebin.com/EC6TX873

Originally crashed when attempting to launch with version 1.2, updated to version 2.3 and the crash remained. Went through the process of removing and adding back mods until TheRCMod was isolated as the cause of the crashing.

**Comment by kreezxil** [comment]
it didn't crash for me. did you report it to the rc mod author? and i need
the cross link when you do.

**Comment by WolfBV** [comment]
They don’t have anywhere for issues to be reported, so I’ll report it in their curseflrge comments section.

**Comment by kreezxil** [comment]
I'll remove this mod next update if they don't have it fixed. I was so
looking forward to using it.

**Comment by WolfBV** [comment]
They’ve responded on their curseforge comments section, not going to directly link to this github report tho.

**Comment by kreezxil** [comment]
mod not fixed in time, removing. will reconsider it later when it gets fixed.

**Comment by kreezxil** [comment]
the way we do this, is when you post on someone's comment stream, you copy
the link id of the comment and paste it here. that's all that is required.

**Comment by WolfBV** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-rc-mod?comment=50
