### ISSUE TITLE
[Bug] Recipe conflict for steel

### ISSUE THREAD

**Issue by Elrol** [kreezxil/World-of-Dragons-A-New-Age#71]
Currently you get steel via the alloy furnace, but there is a recipe to make steel via the blast furnace (the mod that adds this is EmbellishCraft) but another mod already adds a recipe to turn iron into refined iron (from Silent's Mechanisms) 

Since we still are able to get steel its not a big issue, but saw it and figured if the recipe could be removed that would be great, or have the recipe fixed for an easier source of steel, either way.

![image](https://user-images.githubusercontent.com/12816881/69279097-44362880-0ba9-11ea-926f-e3f19bdfad3d.png)

**Comment by kreezxil** [comment]
i tried, i can't knock out the rogue recipe. I can add a recipe that
changes between the two. like after you got the one that is made
regardless, i can then have that one change to the other in a grid or in
the furnace even. ie , recook it.

**Comment by kreezxil** [comment]
yep, fixed with my own furnace smelting recipes.
