### ISSUE TITLE
Ma-Essentials removed

### ISSUE THREAD

**Issue by Elrol** [kreezxil/World-of-Dragons-A-New-Age#72]
Since Ma-Essentials was removed we no longer have access to our old homes, and that will cause a bunch of issues for other players. I would suggest that it be put back in for a week or so to allow players to change homes, or upon request change the files manually (I could do it if you needed)

**Comment by kreezxil** [comment]
yes but we have the data for it. so I'll provide a link to the folder. Look in the #adll-admin channel in the pins I provide a web based interface for accessing server files. Get with @Tarlin83 if you don't  understand how to use it.
