### ISSUE TITLE
Refined Storage Grid GUI failure?

### ISSUE THREAD

**Issue by Soutemumb** [kreezxil/World-of-Dragons-A-New-Age#74]
I have a Refined Storage system at my base, but after the latest update I can no-longer open up specifically the Grid's GUI (And as a bonus I cannot open it via wireless grid either)
I've unplugged it and plugged it back in ~(ᴹᵉᵃⁿᶦⁿᵍ ᴵ ᵇʳᵒᵏᵉ ᵗʰᵉ ᵇˡᵒᶜᵏ ᵃⁿᵈ ʳᵉᵖˡᵃᶜᵉᵈ ᶦᵗ)~ **IF YOU GOT SOMETHING TO SAY MAKE SURE WE CAN READ IT** and the block is still drawing power and can be seen in the Refined Storage Controller.

**Comment by kreezxil** [comment]
#58 goes along with this and that means he didn't fix that issue.

**Comment by kreezxil** [comment]
@Soutemumb I need you to wipe your logs folder for the pack.

then access your rs system in the way that you described above.

verify that you can't access it.

then exit your client and attach the latest.log here

just drag and drop it, don't open it and copy paste. no need for that.

![image](https://user-images.githubusercontent.com/3880072/69499373-13ab0300-0eb7-11ea-825c-fb1da789fe1c.png)

**Comment by kreezxil** [comment]
We're going to need this to make the case.

**Comment by Soutemumb** [comment]
I'm afraid after the update that I cannot replicate the problem, Thanks for trying Kree!
