### ISSUE TITLE
Minecolonies NPC trapped by boat

### ISSUE THREAD

**Issue by Soutemumb** [kreezxil/World-of-Dragons-A-New-Age#75]
![2019-11-22](https://user-images.githubusercontent.com/37351266/69406529-e51b0580-0cc7-11ea-9b1a-6193cd2bfbac.png)
My hardworking builder has gotten trapped in a boat left in my colony and I cannot get him out for whatever reason. 
I've tried hitting the boat out from under him but it hurts him in the process.

**Comment by kreezxil** [comment]
go to the npc's hut block and choose "recall"

**Comment by CriswellCodes** [comment]
Resolved and closing
