### ISSUE TITLE
Minecolonies armor incompatibility with Mine and Slash crafted armor

### ISSUE THREAD

**Issue by Soutemumb** [kreezxil/World-of-Dragons-A-New-Age#76]
Colony guard NPCs cannot wear crafted vanilla armor after it's converted to mine and slash armor with it's stats.

**Comment by AzureDoom** [comment]
This sounds like an issue for Minecolonies to fix.

**Comment by kreezxil** [comment]
@azuredoom maybe you can provide a method to autocompat such that if a
vanilla crafted armor is crafted against a cactus or flint, the attributes
are scraped off restoring it to pure vanilla.

**Comment by marchermans** [comment]
I work on minecolonies, and we basically just ask the armor for its level and type
That is it.
If the worker and hut are leveled up enough the armor is allowed for the guards to be worn.
@kreezxil Do you guys do something special with your items to make them some kind of fake armor?

**Comment by AzureDoom** [comment]
The armor gain extra NBT via the mod Mine and Slash. This bit of NBT is causing the issue.

**Comment by kreezxil** [comment]
please check in todays update of the patch to see if this issue has been resolves

@Soutemumb @AzureZhen @OrionDevelopment @Tarlin83

**Comment by Soutemumb** [comment]
The bug hasn't been solved, the guard in my minecolony still refuses to wear the armor.

**Comment by kreezxil** [comment]
@AzureZhen minecolonies teams says they can't fix this problem. Can you patch autocompat to not change the values of vanilla armor?

**Comment by AzureDoom** [comment]
@kreezxil there is an config option just for this reason. Just go ahead and turn it to false. It will disable the Vanilla items getting stats.

**Comment by kreezxil** [comment]
ok, i didn't know that was there.
