### ISSUE TITLE
Minecolonies Bugs

### ISSUE THREAD

**Issue by Newt121** [kreezxil/World-of-Dragons-A-New-Age#78]
when citizens in Nordic hut going down the ladder in 4 togather noone is possible to go down and they get stucked upstairs.
![image](https://user-images.githubusercontent.com/57691826/69643128-26fad180-1063-11ea-9202-24e237056d02.png)

**Comment by kreezxil** [comment]
please one issue per report.

which means I need you to separate this. Each one you make is the head of a
trail to get them fixed. If they're all in one then to the outside world
this report will never looked resolved.

**Comment by kreezxil** [comment]
@Newt121 @Tarlin83 See if this has been fixed in today's patch.

**Comment by kreezxil** [comment]
dev team says it's a known issue

**Comment by Raycoms** [comment]
@kreezxil you can close this, will be fixed in the next patch
