### ISSUE TITLE
Minecolonies Nordic Miner 

### ISSUE THREAD

**Issue by Newt121** [kreezxil/World-of-Dragons-A-New-Age#79]
Nordic miner is mining his Minelevels and also the Ladder
![image](https://user-images.githubusercontent.com/57691826/69642291-d0d95e80-1061-11ea-992e-7037f448b529.png)
![image](https://user-images.githubusercontent.com/57691826/69642330-dfc01100-1061-11ea-9cf3-b508dd3f0f21.png)

**Comment by kreezxil** [comment]
@Newt121 see if this has been fixed in todays patch

**Comment by kreezxil** [comment]
dev team says this is fixed
