### ISSUE TITLE
Rf tool's Utilities Screen crashes client

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/World-of-Dragons-A-New-Age#83]
The RF tool's Utilities screen crashes the client when placed, but was actually placed so anytime i get on it crashes me again. I also attached a crash report on it.
[crash-2019-11-28_21.49.42-client.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3903680/crash-2019-11-28_21.49.42-client.txt)
https://github.com/McJtyMods/RFToolsUtility/issues/8#issue-530144489

**Comment by kreezxil** [comment]
mcjty says it's a bug in forge and when the version that fixes it in forge is merged in, that's when this becomes fixed. leaving this open until we know it's no longer related to forge.
