### ISSUE TITLE
server crash when interacting with a lvl 1 citizen hut

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons-A-New-Age#88]
the server crashes whenever i open the lvl 1 citizen hut gui,other than that it also crashed 2 times when i was just exploring(i didnt pick up any unsual item it just crashed out of nowhere)

how to reproduce: right click a lvl 1 citizen hut from minecolonies ( if that didnt crash it then try assigning a colony citizen to it)

Relevant logs, if any:
[crash-2019-12-04_13.18.45-server.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3927706/crash-2019-12-04_13.18.45-server.txt)
[crash-2019-12-04_14.00.43-server.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3927707/crash-2019-12-04_14.00.43-server.txt)
[crash-2019-12-04_14.01.44-server.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3927708/crash-2019-12-04_14.01.44-server.txt)
[crash-2019-12-04_13.19.45-server.txt](https://github.com/kreezxil/World-of-Dragons-A-New-Age/files/3927709/crash-2019-12-04_13.19.45-server.txt)

**Comment by AzureDoom** [comment]
Seems the two more updates have come out since Kreezxil updated, they look like they fix these crashes. 
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2836611
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2836641

**Comment by kreezxil** [comment]
@ParsaMT @AzureZhen see if this has been fixed in todays patch

**Comment by kreezxil** [comment]
a forge problem they said

**Comment by kreezxil** [comment]
devteam says this fixed
