### ISSUE TITLE
Armor is disapearing from equipment slots

### ISSUE THREAD

**Issue by Soutemumb** [kreezxil/World-of-Dragons-A-New-Age#89]
Armor pieces have gone missing from equipment slots. It seemed random at first but Mine and Slash effected armor is breaking instead of remaining at low durability, putting an indicator on-screen, and removing the stats the armor gave to the player until it was repaired in the mine and slash gear repair station.

**Comment by kreezxil** [comment]
data to track this is missing ... closing for now. although I'm sure it's related to M&S
