### ISSUE TITLE
[please fix] Armors from Silent Gear not scaling with M&S

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/World-of-Dragons-A-New-Age#9]
The custom armors you can make from blueprints from the [Silent Gear](https://www.curseforge.com/minecraft/mc-mods/silent-gear) mod do not scale, though weapons do. Not sure if a bug or not, but since weapons scale, it's logical to conclude armors should too.

**Comment by kreezxil** [comment]
this is likely an issue between M&S and SG

**Comment by kreezxil** [comment]
I haven't reported it yet. Today's patch doesn't include anything in regards to this report.

**Comment by kreezxil** [comment]
I'm not even sure who to report this too. Probably the M&S team. Ok, I reported it.

**Comment by CriswellCodes** [comment]
Needs crosslink.

**Comment by AzureDoom** [comment]
I created an issue for this https://github.com/SilentChaos512/Silent-Gear/issues/79 along with the referenced PR above.

**Comment by CriswellCodes** [comment]
Just checked with the compatibility mod to see if this issue was resolved, and hand crafted blueprint armor is not fixed with the compat. No reply from silent gear as to a resolution yet.

**Comment by AzureDoom** [comment]
I have not done it in the Compatibility mod as I already opened a PR to the Silent Gear mod to fix the armor so I'd rather not release a mod that will be overridden once the mod it tries to compat updates. I will give the Silent Gear team a week, after that, I will add it to the Compatibility mod.

**Comment by AzureDoom** [comment]
Talked to SilentChaos512 on their discord, Said they'll try and merge my PR for armor Tuesday/Wednesday.

**Comment by kreezxil** [comment]
fixed with auto compat

**Comment by AzureDoom** [comment]
If you are talking about my Auto Compatibility mod, I don't do Silent Gears stuff in it since it's already built in to Silent Gears. Just awaiting my PR to be merged for it to fix the armor.
