### ISSUE TITLE
minecolonies: builder's hut

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/World-of-Dragons-A-New-Age#93]
So i had my builder craft a builder's hut yet it says its finished but the construction tape is in the wrong direction and when it actually finishes i eventually get spammed by the builder that its finished but when i look in the hut block it only gives an option to cancel build not to upgrade it.
![2019-12-09_19 55 00](https://user-images.githubusercontent.com/50385859/70485875-2b40d900-1abe-11ea-9431-4f8b791923b8.png)

**Comment by kreezxil** [comment]
fixed in an upcoming patch
