### ISSUE TITLE
New mods to add : EnderIO and rftools

### ISSUE THREAD

**Issue by Skynder2** [kreezxil/World-of-Dragons-A-New-Age#99]
Here is the link on CurseForge :
https://www.curseforge.com/minecraft/mc-mods/ender-io
https://www.curseforge.com/minecraft/mc-mods/rftools

Thanks you ^^

**Comment by kreezxil** [comment]
added

**Comment by kreezxil** [comment]
actually ender io not added as it is only still for 1.12.2

**please research** the mc/forge version required when suggesting mods. That onus is on you. It saves you having to hear me or some other pack dev telling you about how you need to research it out.

Actually most will just close the ticket and call it invalid.

Also please only 1 ticket per request. 

2 links == 2 requests.

**Comment by kreezxil** [comment]
double crap niether is the RFTOOLS you suggested.

I suspect you fanboy suggested these to me.

Now thankfully I know that the rftools suite is on 1.14.4 and not via the link you gave me, so I will add it. But honestly in the future please do a better job of this.

**Comment by kreezxil** [comment]
wth?!! you didn't even look at the pack before suggesting these things.

RFTOOLS is already in here!

**Comment by Skynder2** [comment]
Oh yes master you are so right the mod is already in the mod pack ( No it is not, so look carefuly before talking )

**Comment by Skynder2** [comment]
And all ther fucking mods are under 1.12.2

**Comment by AzureDoom** [comment]
Hey dumbass @Skynder2 you do know this for the 1.14.4 pack World of Dragons New Age right? Dumbass.
